[custom]
;规则集定义
ruleset=➡️ 国内,https://raw.githubusercontent.com/HelayGo/gugu/refs/heads/main/115.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/HelayGo/gugu/refs/heads/main/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🤖 AI,https://raw.githubusercontent.com/HelayGo/gugu/refs/heads/main/AI.list
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🐬 X,https://raw.githubusercontent.com/HelayGo/gugu/refs/heads/main/Twitter.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=📲  Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/HelayGo/gugu/refs/heads/main/Youtube.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🌍 国外,https://raw.githubusercontent.com/HelayGo/gugu/refs/heads/main/Proxylite.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=➡️ 国内,[]FINAL

custom_proxy_group=🍀 Google`select`[]DIRECT`[]👻 idx节点`[]🌐 Noproxyip`[]🔯 Noproxyip`[]🌐 Jolly`[]🔯 Jolly故转`[]REJECT
custom_proxy_group=🤖 AI`select`[]DIRECT`[]👻 idx节点`[]🌐 Noproxyip`[]🔯 Noproxyip`[]🌐 Jolly`[]🔯 Jolly故转`[]REJECT
custom_proxy_group=🐬 X`select`[]DIRECT`[]👻 idx节点`[]🌐 Noproxyip`[]🔯 Noproxyip`[]🌐 Jolly`[]🔯 Jolly故转`[]REJECT
custom_proxy_group=👨🏿‍💻 GitHub`select`[]DIRECT`[]👻 idx节点`[]🌐 Noproxyip`[]🔯 Noproxyip`[]🌐 Jolly`[]🔯 Jolly故转`[]REJECT
custom_proxy_group=📲  Telegram`select`[]DIRECT`[]👻 idx节点`[]🌐 Noproxyip`[]🔯 Noproxyip`[]🌐 Jolly`[]🔯 Jolly故转`[]REJECT
custom_proxy_group=📹 YouTube`select`[]DIRECT`[]👻 idx节点`[]🌐 Noproxyip`[]🔯 Noproxyip`[]🌐 Jolly`[]🔯 Jolly故转`[]REJECT
custom_proxy_group=🌍 国外`select`[]DIRECT`[]👻 idx节点`[]🌐 Noproxyip`[]🔯 Noproxyip`[]🌐 Jolly`[]🔯 Jolly故转`[]REJECT
custom_proxy_group=➡️ 国内`select`[]DIRECT`[]REJECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]REJECT


custom_proxy_group=👻 idx节点`select`(idx)
custom_proxy_group=🌐 Noproxyip`select`(noproxyip)
custom_proxy_group=🌐 Jolly`select`(jolly)

custom_proxy_group=🔯 Jolly故转`fallback`(?=.*(jolly))^((?!(游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 Noproxyip`fallback`(?=.*(noproxyip))^((?!(游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,50

;设置分组标志位

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true
